### PR TITLE
docs: add Vuepress docs

### LINKED ISSUE #4: [Enhancement] Add contributing guidelines, code of conduct, readme, issue and PR templates, docs
# TODO
- [x] `CONTRIBUTING.md`
- [x] `CODE_OF_CONDUCT.md`
- [x] `ISSUE_TEMPLATE.md`
  - [x] Bug report
  - [x] Feature request
- [x] `PULL_REQUEST_TEMPLATE.md`
- [ ] Docs (e.g. `vuepress`). See #13
- [x] `README.md`

### PR DESCRIPTION
**Pull request by sh7dm**
# Description
Add Vuepress docs.
# Why is this change required?
Fixes #4
- [x] I've read the contributing guidelines and the Code of Conduct
## TODO
- [x] Add basic Vuepress docs
- [x] Add component API
- [x] Add usage examples
- [x] i18n
  - [x] Russian (@sh7dm)
  - Any other languages? If you can translate docs, plz add your language and username to this list. Use 29fd020 as the example.
- [x] Add auto-deployment
- [ ] Change branch
```diff
    docsDir: 'docs',
-   docsBranch: 'vuepress', // TODO: change to `master` before merging
+   docsBranch: 'master',
    editLinks: true,
```

### CODE REVIEW

**Comment by sh7dm** [comment]
Hmm... It seems that Vuepress doesn't support Node v6

**Comment by ericcornelissen** [comment]
Any particular reason you want to support Node v6 @sh7dm? Otherwise I would just remove it from the Travis CI configuration

**Comment by sh7dm** [comment]
@ericcornelissen ok. or we can ignore `engines` option in CI

**Comment by ericcornelissen** [comment]
Unless you really want to support Node v6 I wouldn't do that, seems like a potentially dangerous thing to do. Image a scenario where a(/another) package requires Node v8 or higher and because of that the build in the Node v6 environment fails.

**Comment by sh7dm** [comment]
@gabrieledarrigo @ericcornelissen is it ready to merge? Please add your reviews and if you want add some features to docs.

**Comment by sh7dm** [comment]
@ericcornelissen OK, I'll merge it!

**Comment by sh7dm** [comment]
I'll use Now for deployment

**Comment by ericcornelissen** [comment]
I'm assuming you mean [Now.sh](https://zeit.co/now) @sh7dm? Why not just use GitHub pages?

**Comment by sh7dm** [comment]
@ericcornelissen hmm ok. let's use GitHub Pages

**Comment by sh7dm** [comment]
@ericcornelissen Thanks for help!

**Comment by ericcornelissen** [comment]
> It works 🚀! Check it out here

Awesome, this is a great starting point!


> Thanks for help!

No problem 👌 You're welcome

**Comment by ericcornelissen** [comment]
> We are ready for the first release!

I'm glad you are so eager to get started. However, before publishing I would like to test the project a bit more thoroughly, perhaps refactor the `renderError` function, make some adjustments for the overall documentation.

I agree that we have a good start already, but given that we're working closely with the main project and the main project itself is a product that existed for quite some time, I think it is more important for this project to work properly then for it to be available a few weeks early.

I'm not criticizing your work, I just want this project to be more refined before making it available to the world. Either way, we have to wait for #22 before moving on anyway 😄 I will try my best to look into all the things listed above by early January 👍

**Comment by ericcornelissen** [comment]
Sorry for the delay @sh7dm, I did a couple of things and after all that is done I agree that we're ready for a first release 👍

**Pull request merged**
