### PR TITLE
[Enhancement] Add unit tests configuration

### PR DESCRIPTION
**Pull request by gabrieledarrigo**
# Description

Added the required dependencies in order to test the component:

- Jest and @types/jest
- ts-jest
- @vue/test-utils

and the jest configuration file using ts-jest preset.

# Why is this change required?

Partially implements https://github.com/sh7dm/vue-simple-icons/issues/5

- [X] I've read the contributing guidelines and the Code of Conduct

### CODE REVIEW

**Comment by sh7dm** [comment]
@gabrieledarrigo what do you think about adding Codecov?

**Comment by gabrieledarrigo** [comment]
> @gabrieledarrigo what do you think about adding Codecov?

Gorgeous idea! Maybe we can create a separate issue?

So, as I understand my pain point was: 

`"esModuleInterop": true`

right?

**Comment by sh7dm** [comment]
@gabrieledarrigo yes, I have found this fix and it works

**Comment by gabrieledarrigo** [comment]
Agree!
Great work, and sorry for my poor apport!

**Comment by sh7dm** [comment]
@gabrieledarrigo thanks!

**Pull request merged**
